apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cleanup-cronjob-daemonset
  namespace: default
  labels:
    k8s-app: cleanup-cronjob
spec:
  selector:
    matchLabels:
      name: cleanup-cronjob-daemonset
  template:
    metadata:
      labels:
        name: cleanup-cronjob-daemonset
    spec:
      containers:
      - name: clean-container-image-daemonset
        image: lachlanevenson/k8s-kubectl:v1.6.12
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/sh
              - -c
              - kubectl delete cronjobs cronjob-cleanup-${NODE_NAME} --namespace=${NAMESPACE}
        command: [ "sh", "-c"]
        args:
        - sed -i "s/NODE_NAME/${NODE_NAME}/g;" /opt/cron-job.yaml;kubectl create -f /opt/cron-job.yaml --namespace=${NAMESPACE}
        volumeMounts:
        - name: dockersock
          mountPath: /var/run/docker.sock
        - name: file
          mountPath: /opt
        env:
         - name: NODE_NAME
           valueFrom:
             fieldRef:
               fieldPath: spec.nodeName
         - name: NAMESPACE
           valueFrom:
             fieldRef:
               fieldPath: metadata.namespace
      terminationGracePeriodSeconds: 180
      restartPolicy: Never
      volumes:
      - name: dockersock
        hostPath:
          path: /var/run/docker.sock
      - name: file
        secret:
          secretName: cron-job-file
